# Generated by Django 4.1.7 on 2023-04-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NSEAPP', '0002_remove_watchlist_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
