# Generated by Django 4.1.7 on 2023-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSEAPP', '0003_alter_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='predicted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
