# Generated by Django 4.1.7 on 2023-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSEAPP', '0003_remove_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
