# Generated by Django 4.1.7 on 2023-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSEAPP', '0004_watchlist_predicted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
    ]
