# Generated by Django 4.1.7 on 2023-04-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NSEAPP', '0005_watchlist_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='industry',
        ),
    ]
